const fakeids = [
  {
    name: "McLovin",
    spawnyear: "06/03/1981",
    expiration: "06/03/2008",
    sex: "M",
    description: "It was between that and Mohammed!",
    price: "0.00",
    imageUrl:
      "https://i.etsystatic.com/7862244/r/il/2008c5/5492816055/il_570xN.5492816055_f00t.jpg",
    altText: "id for mclovin",
  },
  {
    name: "Jordan H. Lane",
    spawnyear: "04/17/2003",
    expiration: "04/17/2030",
    sex: "M",
    description: "Looks like a frat guy, think he got in some trouble with cops once for drunk driving",
    price: "5.18",
    imageUrl: "",
    altText: "",
  },
  {
    name: "Emily S. Archer",
    spawnyear: "12/22/1985",
    expiration: "12/22/2028",
    sex: "F",
    description: "Middle aged white women, HOA president so it might come in handy",
    price: "27.01",
    imageUrl: "",
    altText: "",
  },
  {
    name: "Ricardo Silvestor",
    spawnyear: "07/09/1998",
    expiration: "07/09/2029",
    sex: "M",
    description: "Looks homeless",
    price: "0.94",
    imageUrl: "",
    altText: "",
  },
  {
    name: "Lily Nguyen",
    spawnyear: "03/04/2005",
    expiration: "03/04/2031",
    sex: "F",
    description: "08, boba, #nyc.. you get my point",
    price: "8.82",
    imageUrl: "",
    altText: "",
  },
  {
    name: "Carlos D. Garcia",
    spawnyear: "11/14/1994",
    expiration: "11/14/2027",
    sex: "M",
    description: "Guy I chatted with at a bar.. dont ask what happened to him",
    price: "17.35",
    imageUrl: "",
    altText: "",
  },
  {
    name: "Zoe Patel",
    spawnyear: "06/30/2002",
    expiration: "06/30/2025",
    sex: "F",
    description: "Black haired with really pretty hazel eyes, hopefully your pretty enough to match up- hehehhehehhe",
    price: "51.98",
    imageUrl: "",
    altText: "",
  },
  {
    name: "Ben J. Roberts",
    spawnyear: "10/08/1995",
    expiration: "10/08/2028",
    sex: "M",
    description: "Brown messy hair and disheveled look, tried making a podcast lolz and it failed, miserably",
    price: "9.21",
    imageUrl: "",
    altText: "",
  },
  {
    name: "Maya Kim",
    spawnyear: "01/19/2003",
    expiration: "01/19/2033",
    sex: "F",
    description: "Blonde hair with pink tips",
    price: "4.76",
    imageUrl: "",
    altText: "",
  },
  {
    name: "Samuel W. Evans",
    spawnyear: "09/25/1983",
    expiration: "09/25/2026",
    sex: "M",
    description: "Another homeless looking one, lol",
    price: "2.09",
    imageUrl: "",
    altText: "",
  },
  {
    name: "Ava T. Brooks",
    spawnyear: "02/15/1997",
    expiration: "02/15/2027",
    sex: "F",
    description: "Grayish red hair, kind of a hippie",
    price: "8.32",
    imageUrl: "",
    altText: "",
  },
  {
    name: "Ethan B. Cooks",
    spawnyear: "12/03/2001",
    expiration: "12/03/2032",
    sex: "M",
    description: "his eyes kind of apart, like your split ends",
    price: "14.19",
    imageUrl: "",
    altText: "",
  },
  {
    name: "Sofia L. Ramirez",
    spawnyear: "07/22/1990",
    expiration: "07/22/2024",
    sex: "F",
    description: "She very short, haha",
    price: "2.08",
    imageUrl: "",
    altText: "",
  },
  {
    name: "Jackson Lin",
    spawnyear: "05/06/2002",
    expiration: "05/06/2035",
    sex: "M",
    description: "copped his id cause he playin valorant, ew",
    price: "1.59",
    imageUrl: "",
    altText: "",
  },
  {
    name: "Amanda Zheng",
    spawnyear: "08/31/2001",
    expiration: "08/31/2035",
    sex: "F",
    description: "Black hair with glasses, you could probably pull it off",
    price: "4.52",
    imageUrl: "",
    altText: "",
  },
  {
    name: "Isabella O. Foster",
    spawnyear: "11/11/2003",
    expiration: "11/11/2058",
    sex: "F",
    description: "Bleach blonde hair with pink sweater",
    price: "1.09",
    imageUrl: "",
    altText: "",
  },
  {
    name: "Micheal Whalen",
    spawnyear: "05/17/1004",
    expiration: "05/17/97518235785",
    sex: "M",
    description: "hohoho merry christmas",
    price: "413126.01",
    imageUrl: "",
    altText: "",
  },
];
export { fakeids };
