const fakeids = [
  {
    name: "McLovin",
    spawnyear: "06/03/1981",
    expiration: "06/03/2008",
    sex: "M",
    description: "It was between that and Mohammed!",
    price: "0.00",
    imageUrl:
      "https://i.etsystatic.com/7862244/r/il/2008c5/5492816055/il_570xN.5492816055_f00t.jpg",
    altText: "id for mclovin",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
  {
    name: "",
    spawnyear: "",
    expiration: "",
    sex: "M",
    description: "",
    price: "",
    imageUrl: "",
    altText: "",
  },
];

export { fakeids };
